---
- name: newrelic agent setup  
  hosts: all
 
  tasks:
    - script: agent-install.sh
    - copy:
        src: newrelic-infra.yml
        dest: /etc/newrelic-infra.yml
    - name: restart newrelic agent
      command: sudo systemctl restart newrelic-infra

