#!/usr/bin/env python3
"""Check that every repository path referenced in the docs actually exists.

A tutorial that says "see ansible/roles/foo/tasks/main.yml" and points at a file
that does not exist is worse than no tutorial. This scans the markdown for
repo-relative paths and reports the broken ones.

    python3 tools/docs_path_check.py
"""

from __future__ import annotations

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent

# Matches things that look like repo-relative paths in backticks or prose.
PATH_RE = re.compile(
    r"(?<![\w/.\-])"
    r"("
    r"(?:ansible|terraform|labs|docs|tools|\.github)/[\w./\-]+"
    r"|(?:README|TUTORIAL|Makefile|\.yamllint|\.checkov|\.gitignore)[\w.\-]*"
    r")"
)

# Extensions/fragments that are not real files on disk.
IGNORE_SUFFIXES = (".md:", ".yml:", ".py:", ".tf:", "/")

# Paths that are deliberately absent: these are exercise deliverables the reader
# is asked to create, or git-ignored generated files quoted inside an example.
# Keep this list small and explain every entry.
INTENTIONAL = {
    # Day 12 exercise: "Write terraform/bootstrap/main.tf that creates the state bucket"
    "terraform/bootstrap/main.tf",
    # Day 21 exercise: "Create terraform/environments/prod/main.tf as a thin wrapper"
    "terraform/environments/prod/main.tf",
    # Day 21 exercise: document intentional environment differences
    "terraform/environments/README.md",
    # Quoted from the GENERATED banner in tf_to_inventory.py; the directory is
    # git-ignored and only exists after a real apply.
    "ansible/inventory/generated/servers.yml",
    # Generated by tf_to_inventory.py, git-ignored, and removed by `make clean`.
    "ansible/inventory/generated/dev.yml",
    # Created by `ansible-galaxy collection install -r requirements.yml`,
    # git-ignored. Does not exist on a fresh checkout (Day 17).
    "ansible/collections",
}


def looks_like_path(candidate: str) -> bool:
    if len(candidate) < 4:
        return False
    if candidate.endswith(IGNORE_SUFFIXES):
        return False
    # Require at least one dot or one slash - otherwise it is a word like "ansible".
    return ("." in candidate or "/" in candidate)


def main() -> int:
    docs = sorted(ROOT.rglob("*.md"))
    docs = [d for d in docs if ".git" not in d.parts]

    missing: dict[str, set[str]] = {}
    checked = 0

    for doc in docs:
        text = doc.read_text(encoding="utf-8")
        for match in PATH_RE.finditer(text):
            candidate = match.group(1).rstrip(".,;:)")
            if not looks_like_path(candidate):
                continue
            # Wildcards and templates are not checkable.
            if "*" in candidate or "{{" in candidate:
                continue
            checked += 1
            if candidate in INTENTIONAL:
                continue
            target = ROOT / candidate
            if not target.exists():
                rel = doc.relative_to(ROOT)
                missing.setdefault(str(rel), set()).add(candidate)

    print(f"scanned {len(docs)} markdown file(s), {checked} path reference(s)")

    if missing:
        print("\nBROKEN REFERENCES:")
        total = 0
        for doc in sorted(missing):
            print(f"  {doc}")
            for candidate in sorted(missing[doc]):
                print(f"     -> {candidate}")
                total += 1
        print(f"\n{total} broken reference(s)")
        return 1

    print("all referenced paths exist")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
